### ISSUE TITLE
Quests are not generated near offshore colonies

### ISSUE THREAD

**Issue by SaintWacko** [joseasoler/Pathfinding-Framework#109]
**Describe the bug**

With an offshore island colony, quests are being generated around what I assume is 0,0 on the world map instead of near the colony. 

**HugsLib log**

https://gist.github.com/HugsLibRecordKeeper/6773f5d3d22320f4289a3a16c35ef720

**To Reproduce**

1. Start a colony on an offshore island
2. Wait for a quest to show up
3. Observe that the quest is in the center of the map instead of near the island colony

**Expected behavior**

I would expect the game to continue to assign quests nearby my colony.

**Screenshots**

<img width="660" alt="Screenshot 2023-12-04 at 19 48 32" src="https://github.com/joseasoler/Pathfinding-Framework/assets/10342141/d268879e-96c4-4def-be05-be623aa03b14">

**Additional context**

This only started occurring once Biomes! Islands updated to use Pathfinding Framework, and I suspect is caused by the fact that the game's quest distance calculator (not being aware of watergoing vehicles) considers all of the mainland to be equally unreachable, and thus defaults to placing quests around the center of the map.

**Comment by joseasoler** [comment]
Thank you for the report!

Before the pathfinding update, Biomes! Islands made all ocean world tiles walkable by caravans. After the update, ocean world tiles are no longer walkable and the player must use drop pods or vehicles. This should not affect quest generation because in vanilla quests are always generated in nearby tiles that fit some condition, even if they are unreachable. I have tested this with a small modlist that includes Biomes! Islands:

![image](https://github.com/joseasoler/Pathfinding-Framework/assets/3092211/b91f2ecf-caba-4a10-bdae-f0309dce5098)

With both this small modlist and my full modlist, quests spawn on either the closest part or the mainland or on nearby islands, depending on the type of the quest:

![image](https://github.com/joseasoler/Pathfinding-Framework/assets/3092211/83fcb0e8-dcd9-411b-a566-bc8edb9a6b98)

My assumption is that some mod in your modlist changes how quests are generated and now requires world tile reachability. Before the pathfinding update all world tiles were reachable so this went unnoticed. After the update, that other mod is no longer able to find any reachable tiles for island colonies and is giving up and placing quests on the center of the map.

After checking your modlist, one of the potential candidates for this behaviour is Save Our Ship 2. It has multiple patches to the quest system, so maybe there is a mod incompatibility there.

**Comment by SaintWacko** [comment]
Hmmm, interesting. Alright, sorry for the mis-report! I'm trying to verify this, but having some trouble actually generating quests through dev mode. They all say `[Not now]` next to them.

**Comment by SaintWacko** [comment]
Ah, just went about it another way and confirmed it was SoS2. Thanks for pointing me in the right direction!

**Comment by joseasoler** [comment]
That is good to know, thanks. Then I assume that a similar issue would happen with just SOS2 and without islands, if the colony starts on a single tile island.

**Comment by SaintWacko** [comment]
That's a good point, I'll bet it would
